### ISSUE TITLE
user and role many-to-many mappings

### ISSUE THREAD

**Issue by voynovia** [BranislavLazic/angular-security#1]
hello, how to set users and roles were related to each other many-to-many?

**Comment by BranislavLazic** [comment]
That is JPA related question. You should probably seek for an answer here: https://dzone.com/tutorials/java/hibernate/hibernate-example/hibernate-mapping-many-to-many-using-annotations-1.html

Focus on this example is securing applications composed from RESTful web service and client side application that uses AngularJS.
