### ISSUE TITLE
Build with gulp 

### ISSUE THREAD

**Issue by lukaszog** [BranislavLazic/angular-security#4]
Yesterday I download this project and I ran npm install and bower install. When I type gulp for run project I get error angular is not defined in js files.

**Comment by BranislavLazic** [comment]
I just checked. `gulp` task works normally after running `npm install` and `bower install`. Please check whether angular files are downloaded in `app/bower_components` directory.

**Comment by lukaszog** [comment]
Hm, It's strange, but on Ubuntu it working everything ok on windows no, I have angular files in `app/bower_components` ok, it's not a problem. I have one question. How to setup register new users?

**Comment by BranislavLazic** [comment]
There's no functionality for that. You will have to implement it by your own. Or simply add them directly to database.

**Comment by lukaszog** [comment]
Ok, on Windows machine I must create `.jshintrc` with 
`{
  "predef": ["angular"]
  }`
I want to implement register new user in which way can I send username and password to rest? Normally or encrypted?

**Comment by BranislavLazic** [comment]
Send it normally.

**Comment by lukaszog** [comment]
This code will work with MongoDB?

**Comment by BranislavLazic** [comment]
Not exactly. But you do not have to make a lot of modifications. You have to add MongoDB Spring Data module. Configure data source properties and map entities properly. Start with Spring Data MongoDB documentation and you should be fine. And yes. You will have to adapt refresh token data store to work with MongoDB. Shouldn't be hard. Frontend code will work normally of course.
